
<?php
//var_dump($block);
//var_dump($_REQUEST);
if(!empty($_REQUEST['ik_inv_st']) && !empty($_REQUEST['ik_pm_no'])) {
    $order = \Magento\Framework\App\ObjectManager::getInstance()->create('\Magento\Sales\Model\Order')->loadByIncrementId((int)$_REQUEST['ik_pm_no']);
    if ($_REQUEST['ik_inv_st'] == 'success')
        echo $block->msgSuccess() . $order->getIncrementId();
    elseif (in_array($_REQUEST['ik_inv_st'], array('fail', 'canceled')))
        echo $block->msgFail() . $order->getIncrementId();
}
?>