<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" crossorigin="anonymous">
<link rel="stylesheet" href="/skin/frontend/interkassa/css/interkassa.css">
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" crossorigin="anonymous"></script>
<div class="interkasssa" style="text-align: center;">
    <img style="display: inline-block; width:300px;" src="/skin/frontend/interkassa/logo_interkassa.png"/>
<?php
$interkassa = $this->getLayout()->createBlock('Interkassa/redirect')->toHtml();

$data = $interkassa -> getDataFormIK();
echo '<form name="payment_interkassa" id="InterkassaForm" action="javascript:selpayIK.selPaysys()" method="POST">';
foreach ($data as $key => $value)
    echo "<input type='hidden' name='$key' value='$value'>";

echo '<button type="submit">Pay via Interkassa</button>
</form>';

if($interkassa->isActiveAPI()) {
    $payment_systems = $interkassa->getPaymentSystems();
    if (is_array($payment_systems) && !empty($payment_systems)) {
        ?>
    <button type='button' class='sel-ps-ik btn btn-info btn-lg' data-toggle='modal' data-target='#InterkassaModal' style='display: none;'>
        Select Payment Method
    </button>

    <div id='InterkassaModal' class='modal fade' role='dialog'>
        <div class='modal-dialog modal-lg'>
            <div class='modal-content' id='plans'>
                <div class='container'>
                    <h1>
                        1.Select Payment Method<br>
                        2.Specify currency<br>
                        3.Press Pay
                    </h1>

                    <div class='row'>
                    <?php
            foreach ($payment_systems as $ps => $info) {
                echo "<div class='col-sm-3 text-center payment_system'>
                            <div class='panel panel-warning panel-pricing'>
                                <div class='panel-heading'>
                                    <div class='panel-image'>
                                        <img src='/skin/frontend/interkassa/images/{$ps}.png' alt='{$info['title']}'>
                                    </div>
                                    <!--<h3>{$info['title']}</h3>-->
                                </div>
                                <div class='form-group'>
                                    <div class='input-group'>
                                        <div class='radioBtn btn-group'>";
                            foreach ($info['currency'] as $currency => $currencyAlias) {
                                echo "<a class='btn btn-primary btn-sm notActive'
                                                   data-toggle='fun' data-title='{$currencyAlias}'>{$currency}</a>";
                            }
                                echo "</div>
                                        <input type='hidden' name='fun' id='fun'>
                                    </div>
                                </div>
                                <div class='panel-footer'>
                                    <a class='btn btn-lg btn-block btn-success ik-payment-confirmation'
                                       data-title='{$ps}'
                                       href='#'>Pay with <br>
                                        <strong>{$info['title']}</strong>
                                    </a>
                                </div>
                            </div>
                        </div>";

            }
            ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    }
    else
        echo $payment_systems;
}
?>
</div>
<script type='text/javascript'>
var selpayIK = {
    actForm: 'https://sci.interkassa.com/',
    req_url: '/Interkassa/selectps/',
    selPaysys: function () {
        if(jQuery('button.sel-ps-ik').length > 0)
            jQuery('.sel-ps-ik').click()
        else{
            var form = jQuery('form[name="payment_interkassa"]')
            form[0].action = selpayIK.actForm
            setTimeout(function(){form[0].submit()},200)
        }
    },
    paystart : function (data) {
        data_array = (this.IsJsonString(data))? JSON.parse(data) : data
        console.log(data_array);
        var form = jQuery('form[name="payment_interkassa"]');
        if (data_array['resultCode'] != 0) {
            jQuery('input[name="ik_act"]').remove();
            jQuery('input[name="ik_int"]').remove();
            jQuery('form[name="payment_interkassa"]').attr('action', selpayIK.actForm).submit()
        }
        else {
            if (data_array['resultData']['paymentForm'] != undefined) {
                var data_send_form = [];
                var data_send_inputs = [];
                data_send_form['url'] = data_array['resultData']['paymentForm']['action'];
                data_send_form['method'] = data_array['resultData']['paymentForm']['method'];
                for (var i in data_array['resultData']['paymentForm']['parameters']) {
                    data_send_inputs[i] = data_array['resultData']['paymentForm']['parameters'][i];
                }
                jQuery('body').append('<form method="' + data_send_form['method'] + '" id="tempformIK" action="' + data_send_form['url'] + '"></form>');
                for (var i in data_send_inputs) {
                    jQuery('#tempformIK').append('<input type="hidden" name="' + i + '" value="' + data_send_inputs[i] + '" />');
                }
                jQuery('#tempformIK').submit();
            }
            else {
                if (document.getElementById('tempdivIK') == null)
                    jQuery('form[name="payment_interkassa"]').after('<div id="tempdivIK">' + data_array['resultData']['internalForm'] + '</div>');
                else
                    jQuery('#tempdivIK').html(data_array['resultData']['internalForm']);
                jQuery('#internalForm').attr('action', 'javascript:selpayIK.selPaysys2()')
            }
        }
    },
    selPaysys2 : function () {
        var form2 = jQuery('#internalForm');
        var msg2 = form2.serialize();
        jQuery.ajax({
            type: 'POST',
            url: selpayIK.req_url,
            data: msg2,
            success: function (data) {
                selpayIK.paystart2(data.responseText);
            },
            error: function (xhr, str) {
                alert('Error: ' + xhr.responseCode);
            }
        });
    },
    paystart2 : function (string) {
        data_array = (this.IsJsonString(data))? JSON.parse(data) : data;
        console.log(data_array);
        var form2 = jQuery('#internalForm');
        if (data_array['resultCode'] != 0) {
            form2[0].action = selpayIK.actForm;
            jQuery('input[name="ik_act"]').remove();
            jQuery('input[name="ik_int"]').remove();
            jQuery('input[name="sci[ik_int]"]').remove();
            setTimeout(function(){form2[0].submit()},200)
        }
        else {
            jQuery('#tempdivIK').html('');
            if (data_array['resultData']['paymentForm'] != undefined) {
                var data_send_form = [];
                var data_send_inputs = [];
                data_send_form['url'] = data_array['resultData']['paymentForm']['action'];
                data_send_form['method'] = data_array['resultData']['paymentForm']['method'];
                for (var i in data_array['resultData']['paymentForm']['parameters']) {
                    data_send_inputs[i] = data_array['resultData']['paymentForm']['parameters'][i];
                }
                jQuery('#tempdivIK').append('<form method="' + data_send_form['method'] + '" id="tempformIK2" action="' + data_send_form['url'] + '"></form>');
                for (var i in data_send_inputs) {
                    jQuery('#tempformIK2').append('<input type="hidden" name="' + i + '" value="' + data_send_inputs[i] + '" />');
                }
                jQuery('#tempformIK2').submit();
            }
            else {
                jQuery('#tempdivIK').append(data_array['resultData']['internalForm']);
            }
        }
    },
    IsJsonString : function(str) {
        try {
            JSON.parse(str);
        } catch (e) {
            return false;
        }
        return true;
    }
}

jQuery(document).ready(function () {
    jQuery('body').prepend('<div class="blLoaderIK"><div class="loaderIK"></div></div>');
    var checkSelCurrPS = []

    jQuery('.ik-payment-confirmation').click(function (e) {
        e.preventDefault();

        var pm = jQuery(this).closest('.payment_system');
        var ik_pw_via = jQuery(pm).find('.radioBtn a.active').data('title')
        if (!jQuery(pm).find('.radioBtn a').hasClass('active') || (jQuery.inArray(ik_pw_via, checkSelCurrPS) == -1)) {
            alert('You did not choose currency');
            return;
        } else {
            if (ik_pw_via.search('test_interkassa|qiwi|rbk') == -1) {
                var form = jQuery('form[name="payment_interkassa"]');
                form.append(
                    jQuery('<input>', {
                        type: 'hidden',
                        name: 'ik_act',
                        val: 'process'
                    }));
                form.append(
                    jQuery('<input>', {
                        type: 'hidden',
                        name: 'ik_int',
                        val: 'json'
                    }));
                jQuery('.blLoaderIK').css('display', 'block');
                jQuery.post(selpayIK.req_url, form.serialize(), function (data) {
                        selpayIK.paystart(data);
                    })
                    .fail(function () {
                        alert('Something wrong');
                    })
                    .always(function () {
                        jQuery('.blLoaderIK').css('display', 'none');
                    })
            }
            else {
                jQuery('form[name="payment_interkassa"]').attr('action', selpayIK.actForm).submit()
            }
        }
        jQuery('#InterkassaModal').hide()
        jQuery('.fade.in').hide()
    });

    jQuery('.radioBtn a').on('click', function () {
        jQuery('.blLoaderIK').css('display', 'block');
        var form = jQuery('form[name="payment_interkassa"]');
        var sel = jQuery(this).data('title');
        var tog = jQuery(this).data('toggle');
        jQuery('#' + tog).prop('value', sel);
        jQuery('a[data-toggle="' + tog + '"]').not('[data-title="' + sel + '"]').removeClass('active').addClass('notActive');
        jQuery('a[data-toggle="' + tog + '"][data-title="' + sel + '"]').removeClass('notActive').addClass('active');

        var ik_pw_via = jQuery(this).attr('data-title');
        checkSelCurrPS.push(ik_pw_via)
        if (jQuery('input[name ="ik_pw_via"]').length > 0)
            jQuery('input[name ="ik_pw_via"]').val(ik_pw_via);
        else
            form.append(jQuery('<input>', {type: 'hidden', name: 'ik_pw_via', val: ik_pw_via}));

        jQuery.post(selpayIK.req_url, form.serialize())
            .always(function (data) {
                jQuery('.blLoaderIK').css('display', 'none');
                if(data.status == 200){
                    jQuery('input[name="ik_sign"]').val(data.responseText);
                }
                else
                    alert('Something wrong');
            })
    })
});
</script>
